// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg0Ygtp2ShtcHtbUO114dEusUbC8COlv0',
    appId: '1:190564077554:web:e2e1941efa03ea5f1ee56b',
    messagingSenderId: '190564077554',
    projectId: 'test-auth-ee62c',
    authDomain: 'test-auth-ee62c.firebaseapp.com',
    storageBucket: 'test-auth-ee62c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwVbWnwlgczdnb906CUrvbo7W0MqQLAcY',
    appId: '1:190564077554:android:65e4c43c394a2bec1ee56b',
    messagingSenderId: '190564077554',
    projectId: 'test-auth-ee62c',
    storageBucket: 'test-auth-ee62c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Xu22do6L7Om85QFKXGShU_MT49UC_GQ',
    appId: '1:190564077554:ios:8beda7d3d50acd751ee56b',
    messagingSenderId: '190564077554',
    projectId: 'test-auth-ee62c',
    storageBucket: 'test-auth-ee62c.appspot.com',
    androidClientId: '190564077554-pa094mbc7d34pq939fmvgsp2q6r2qgod.apps.googleusercontent.com',
    iosClientId: '190564077554-tuod7tbqq832b3i9c6giu8gd8sbsq03d.apps.googleusercontent.com',
    iosBundleId: 'com.example.apaniot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Xu22do6L7Om85QFKXGShU_MT49UC_GQ',
    appId: '1:190564077554:ios:f9747a66d44533031ee56b',
    messagingSenderId: '190564077554',
    projectId: 'test-auth-ee62c',
    storageBucket: 'test-auth-ee62c.appspot.com',
    androidClientId: '190564077554-pa094mbc7d34pq939fmvgsp2q6r2qgod.apps.googleusercontent.com',
    iosClientId: '190564077554-8k59481bs4068uumr573a49nubfskdil.apps.googleusercontent.com',
    iosBundleId: 'com.example.apaniot.RunnerTests',
  );
}
